module.exports = [
  {
    title: "Salt Lake Stadium",
    description: "",
    capacity: "85,000",
    city: "Kolkata",
    country: "India",
  },
  {
    title: "Borg El Arab Stadium",
    description: "",
    capacity: "86,000",
    city: "Alexandria",
    country: "Egypt",
  },
  {
    title: "Bukit Jalil National Stadium",
    description: "",
    capacity: "87,411",
    city: "Kuala Lumpur",
    country: "Malaysia",
  },
  {
    title: "Estadio Azteca",
    description: "",
    capacity: "87,523",
    city: "Mexico city",
    country: "Mexico",
  },
  {
    title: "Wembley Stadium",
    description: "",
    capacity: "90,000",
    city: "London",
    country: "England",
  },
  {
    title: "Rose Bowl Stadium",
    description: "",
    capacity: "90,888",
    city: "Pasadena, California",
    country: "USA",
  },
  {
    title: "FNB Stadium",
    description: "",
    capacity: "94,736",
    city: "Johannesburg",
    country: "South Africa",
  },
  {
    title: "Camp Nou",
    description: "",
    capacity: "99,354",
    city: "Barcelona",
    country: "Spain",
  },
  {
    title: "Melbourne Cricket Ground",
    description: "",
    capacity: "100,024",
    city: "Melbourne",
    country: "Australia",
  },
  {
    title: "Rungrado 1st of May Stadium",
    description: "",
    capacity: "114,000",
    city: "PyongYang",
    country: "North Korea",
  },
];